steps:
  # Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/sound-potion-435303-h4/arjun-100990351/gcp-assignment2-service:${SHORT_SHA}', 
           '.']

  # Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/sound-potion-435303-h4/arjun-100990351/gcp-assignment2-service:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'gcp-assignment2-service'
    - '--image'
    - 'us-central1-docker.pkg.dev/sound-potion-435303-h4/arjun-100990351/gcp-assignment2-service:${SHORT_SHA}'
    - '--region'
    - 'us-central1'
    
images:
  - 'us-central1-docker.pkg.dev/sound-potion-435303-h4/arjun-100990351/gcp-assignment2-service:${SHORT_SHA}'
  
options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
