services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 8080  # ✅ Fix: Explicitly set PORT to 8080
    ports:
      - 8080:8080  # ✅ Fix: Change from 3000:3000 to 8080:8080

